app/uk/gov/hmrc/pillar2externalteststub/validation/ValidationError.scala, app/uk/gov/hmrc/pillar2externalteststub/validation/ValidationResult.scala, app/uk/gov/hmrc/pillar2externalteststub/validation/ValidationRule.scala, app/uk/gov/hmrc/pillar2externalteststub/validation/ValidationSyntax.scala, test/uk/gov/hmrc/pillar2externalteststub/validation/ValidationResultSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/validation/ValidationRuleSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/validation/ValidationSyntaxSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/validation/models/TestValidationError.scala
This PR introduces a validation framework using cats' `ValidatedNec` that supports both accumulative and fail-fast validation strategies. The framework is designed to be generic, type-safe, and reusable across different validation needs.
- Type-safe validation using cats' `Validated` and `NonEmptyChain`
- Flexible validation strategies (accumulate errors or fail-fast)
- Composable validation rules
- Clean syntax for validation through implicits
- validation strategy defined at rule composition time
```scala
// Define a validation error
case class MinLengthError(field: String, minLength: Int) extends ValidationError {
override def errorCode: String = "MIN_LENGTH"
override def errorMessage: String = s"Must be at least $minLength characters"
}
// Create a simple validation rule
val nameRule …
```
=> PIL-1358 Validation Framework

app/uk/gov/hmrc/pillar2externalteststub/models/uktr/repsonse/SubmitUKTRSuccessResponse.scala
For Json schema validation in api tests, this change was made.
=> Updated processingDate from LocalDateTime to ZonedDateTime.

app/uk/gov/hmrc/pillar2externalteststub/controllers/AmendUKTRController.scala, app/uk/gov/hmrc/pillar2externalteststub/controllers/SubmitUKTRController.scala, app/uk/gov/hmrc/pillar2externalteststub/helpers/SubscriptionHelper.scala, app/uk/gov/hmrc/pillar2externalteststub/models/error/StubError.scala, app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRError.scala, app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRSubmission.scala, app/uk/gov/hmrc/pillar2externalteststub/repositories/OrganisationRepository.scala, app/uk/gov/hmrc/pillar2externalteststub/repositories/UKTRSubmissionRepository.scala, build.sbt, it/test/uk/gov/hmrc/pillar2externalteststub/UKTRSubmissionISpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/AmendUKTRControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/StubErrorHandlerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/SubmitUKTRControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/SubscriptionControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/UKTRDataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/repositories/UKTRSubmissionRepositorySpec.scala, test/uk/gov/hmrc/pillar2externalteststub/services/OrganisationServiceSpec.scala
- Added a repository for UKTR submissions (UKTRSubmissionsRepository)
- _insert_ and _update_ corresponding to submitUKTR and amendUKTR, respectively
```json
{
"_id": "67ae24e073366f26ed006e8d",
"pillar2Id": "XEPLR5555555555",
"isAmendment": false,
"data": {
"accountingPeriodFrom": "2024-08-14",
"accountingPeriodTo": "2024-12-14",
"obligationMTT": false,
"electionUKGAAP": false,
"liabilities": {
"electionDTTSingleMember": false,
"electionUTPRSingleMember": false,
"numberSubGroupDTT": 4,
"numberSubGroupUTPR": 5,
"totalLiability": 10000.99,
"totalLiabilityDTT": 5000.99,
"totalLiabilityIIR": 4000,
"totalLiabilityUTPR": 10000.99,
"liableEntities": [
{
"ukChargeableEntityName": "New Company",
"idType": "CRN",
"idValue": "1234",
"amountOwedDTT": {
"$numberLong": "12345678901"
}, …
```
=> PIL-1639: Add UKTR mongodb persistence

app/uk/gov/hmrc/pillar2externalteststub/models/uktr/mongo/UKTRMongoSubmission.scala, app/uk/gov/hmrc/pillar2externalteststub/repositories/OrganisationRepository.scala, app/uk/gov/hmrc/pillar2externalteststub/repositories/UKTRSubmissionRepository.scala, it/test/uk/gov/hmrc/pillar2externalteststub/UKTRSubmissionISpec.scala, test/uk/gov/hmrc/pillar2externalteststub/repositories/UKTRSubmissionRepositorySpec.scala
- Replaced JsObject with typed UKTRMongoSubmission model for better type safety
- Renamed `createdAt` field to `submittedAt` for consistency with BTN
- Updated index structure to include compound index on `pillar2Id` and `submittedAt`
=> PIL-1698: Refactor UKTR to use a typed Mongo model

app/uk/gov/hmrc/pillar2externalteststub/repositories/BTNSubmissionRepository.scala, app/uk/gov/hmrc/pillar2externalteststub/repositories/OrganisationRepository.scala, app/uk/gov/hmrc/pillar2externalteststub/repositories/UKTRSubmissionRepository.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/BTNControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/BTNDataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/Pillar2DataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/UKTRDataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/repositories/BTNSubmissionRepositorySpec.scala, test/uk/gov/hmrc/pillar2externalteststub/repositories/OrganisationRepositorySpec.scala, test/uk/gov/hmrc/pillar2externalteststub/repositories/UKTRSubmissionRepositorySpec.scala
- Enabled deletion by `pillar2Id` in both _UKTR_ and _BTN_ collections
- Added side effects to `testOrg/DELETE` to wipe records in the two collections
=> PIL-1644: Clear submission data upon testOrg deletion

app/uk/gov/hmrc/pillar2externalteststub/controllers/ObligationsAndSubmissionsController.scala, it/test/uk/gov/hmrc/pillar2externalteststub/ObligationsAndSubmissionsISpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/ObligationsAndSubmissionsControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/TestOrgDataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/repositories/ObligationsAndSubmissionsRepositorySpec.scala
This updates the Obligations and Submissions functionality to support organisations with submissions across multiple accounting periods. Adds a bit of future-proofness so we don't have to re-do too much of this implementation later on. 
We essentially move away from using the organisation's accounting period and construct the output purely from the submissions.
This also adds a missing Integration test suite
=> PIL-1816 - Proposal

API Testing/02-orn/Amend ORN - valid request.bru, API Testing/02-orn/Get ORN - no submission.bru, API Testing/02-orn/Get ORN - valid request.bru, API Testing/02-orn/Submit ORN - 500 pillarId.bru, API Testing/02-orn/Submit ORN - duplicate submission.bru, API Testing/02-orn/Submit ORN - invalid date.bru, API Testing/02-orn/Submit ORN - invalid json.bru, API Testing/02-orn/Submit ORN - missing header.bru, API Testing/02-orn/Submit ORN - unauthorized.bru, API Testing/02-orn/Submit ORN - valid request.bru, API Testing/bruno.json, API Testing/environments/local.bru, app/uk/gov/hmrc/pillar2externalteststub/controllers/ORNController.scala, app/uk/gov/hmrc/pillar2externalteststub/models/orn/ORNGetResponse.scala, app/uk/gov/hmrc/pillar2externalteststub/models/orn/ORNRequest.scala, app/uk/gov/hmrc/pillar2externalteststub/models/orn/ORNResponse.scala, app/uk/gov/hmrc/pillar2externalteststub/models/orn/mongo/ORNSubmission.scala, app/uk/gov/hmrc/pillar2externalteststub/repositories/ORNSubmissionRepository.scala, app/uk/gov/hmrc/pillar2externalteststub/repositories/OrganisationRepository.scala, app/uk/gov/hmrc/pillar2externalteststub/services/ORNService.scala, conf/app.routes, it/test/uk/gov/hmrc/pillar2externalteststub/ORNISpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/ORNControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/ORNDataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/repositories/ORNSubmissionRepositorySpec.scala, test/uk/gov/hmrc/pillar2externalteststub/services/ORNServiceSpec.scala
This PR implements the three required endpoints for Overseas Return Notification (ORN) to our external test stub:
- **POST /RESTAdapter/PLR/overseas-return-notification** - Submit a new ORN
- **PUT /RESTAdapter/PLR/overseas-return-notification** - Amend an existing ORN
- **GET /RESTAdapter/PLR/overseas-return-notification** - Retrieve the latest ORN for a specific accounting period
- Created new models:
- `ORNRequest` - For handling submission and amendment payloads
- `ORNSubmission` - MongoDB model for storing submissions
- `ORNGetResponse` - Response model for GET requests
- Implemented core components:
- `ORNController` - Handles HTTP requests with proper error responses
- `ORNService` - Business logic including duplicate checking
- `ORNSubmissionRepository` - MongoDB data access with …
=> PIL-1629 - Add ORN endpoints

app/uk/gov/hmrc/pillar2externalteststub/controllers/StubErrorHandler.scala, app/uk/gov/hmrc/pillar2externalteststub/controllers/package.scala, app/uk/gov/hmrc/pillar2externalteststub/models/btn/BTNValidator.scala, app/uk/gov/hmrc/pillar2externalteststub/models/error/ETMPError.scala, it/test/uk/gov/hmrc/pillar2externalteststub/BTNISpec.scala, it/test/uk/gov/hmrc/pillar2externalteststub/ORNISpec.scala, it/test/uk/gov/hmrc/pillar2externalteststub/UKTRSubmissionISpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/AmendUKTRControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/BTNControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/ORNControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/StubErrorHandlerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/SubmitUKTRControllerSpec.scala
002 - Pillar 2 missing or invalid → **089 - ID number missing or invalid**
004 - Duplicate submission acknowledgment reference → **004 - Duplicate submission**
007 - Business partner does not have an Active subscription → **063 - Business Partner does not have an Active Subscription for this Regime**
=> PIL-1769: Update ETMP APIs errors

app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRLiabilityReturn.scala, it/test/uk/gov/hmrc/pillar2externalteststub/ObligationsAndSubmissionsISpec.scala, it/test/uk/gov/hmrc/pillar2externalteststub/UKTRSubmissionISpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/AmendUKTRControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/SubmitUKTRControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRLiabilityReturnSpec.scala
Update field validation in the stub to send a 400 rather than a 422 when the number field entry is not in this range minimum: 0
maximum: 9999999999999.99
=> PIL-1780 Added logic to alter the bounds and return status

app/uk/gov/hmrc/pillar2externalteststub/models/common/MonetaryReads.scala, app/uk/gov/hmrc/pillar2externalteststub/models/uktr/Liabilities.scala, app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRLiabilityReturn.scala, app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRValidationRules.scala, it/test/uk/gov/hmrc/pillar2externalteststub/UKTRSubmissionISpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/AmendUKTRControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/SubmitUKTRControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/models/common/MonetaryReadsSpec.scala
This PR refactors the validation for monetary fields (like liabilities and amounts owed) to occur during JSON deserialization rather than as a separate business rule validation step.
**Changes:**
*   Introduced `MonetaryReads.monetaryValueReads`, a custom Play JSON `Reads[BigDecimal]`, which ensures values are non-negative, within the maximum allowed limit (`9999999999999.99`), and have a maximum scale of 2 decimal places.
*   Applied this custom `Reads` to the relevant `BigDecimal` fields in the `Liability` and `LiableEntity` models. This implicitly uses the `monetaryValueReads` whenever these models are parsed from JSON.
*   Removed the now-redundant `isValidUKTRAmount` checks and associated validation rules (`amountOwed*Rule`) from `UKTRLiabilityReturn` and `UKTRValidationRules`. The …
=> PIL-1780 - Update boundary check on UKTR

app/uk/gov/hmrc/pillar2externalteststub/models/error/ETMPError.scala, app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRLiabilityReturn.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/StubErrorHandlerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRLiabilityReturnSpec.scala
Adds more business validation rules to submissions from domestic-only organisations (best summarised in the ticket [PIL-1826](https://jira.tools.tax.service.gov.uk/browse/PIL-1826)).
=> PIL-1826: Domestic-only obligationMTT & totals validation

app/uk/gov/hmrc/pillar2externalteststub/services/BTNService.scala, app/uk/gov/hmrc/pillar2externalteststub/services/UKTRService.scala, it/test/uk/gov/hmrc/pillar2externalteststub/BTNISpec.scala, it/test/uk/gov/hmrc/pillar2externalteststub/UKTRSubmissionISpec.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/ObligationsAndSubmissionsDataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/UKTRDataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/services/BTNServiceSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/services/UKTRServiceSpec.scala
This PR implements proper error handling for duplicate submissions of UKTR and BTN
1. **UKTR Service Implementation**
- Added validation to prevent duplicate UKTR submissions
- Implemented 422:044 error response with "Tax Obligation already fulfilled" message
2. **BTN Service Implementation**
- Added validation to check the latest submission via the obligations and submissions repository
- If the latest submission is a BTN, we reject with 422:044 error
- If the latest submission is not a BTN (e.g., a UKTR), we allow the submission
- Fixed previous behavior that returned 422:004 instead of 422:044
=> PIL-1818 Implement Duplicate Submission Error Handling for UKTR and BTN

app/uk/gov/hmrc/pillar2externalteststub/controllers/ObligationsAndSubmissionsController.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/ObligationsAndSubmissionsControllerSpec.scala
**Limit Obligations and submissions to the retrieve the latest 10 Submissions per Accounting Period**
This PR introduces logic to restrict the number of retrieved submissions per obligation type to the latest 10 submissions for each accounting period.
**Changes:**
**For UKTR obligations (including BTN and UKTR):**
Only the latest 10 submissions are returned.
Older submissions beyond the 10th (if any) are excluded.
**For GIR obligations (ORN):**
Only the latest 10 submissions are returned.
Older submissions beyond the 10th (if any) are excluded.
Submissions are sorted by submittedAt in descending order, ensuring the most recent ones are shown first.
Unit tests added to test this functionality
=> PIL-1910 : External test stubs to return latest 10 submissions for each obligations

app/uk/gov/hmrc/pillar2externalteststub/controllers/actions/AuthActionFilter.scala, it/test/uk/gov/hmrc/pillar2externalteststub/UKTRSubmissionISpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/SubscriptionControllerSpec.scala
Return 401 instead of 403. This code should never be reached as a missing Authorization would be stopped at the API layer, but kept here for added safety.
=> PIL-1866: Missing Authorization to return 401

app/uk/gov/hmrc/pillar2externalteststub/models/btn/BTNValidationError.scala, app/uk/gov/hmrc/pillar2externalteststub/models/orn/ORNValidationRules.scala, app/uk/gov/hmrc/pillar2externalteststub/models/orn/ORNValidator.scala, app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRSubmission.scala, app/uk/gov/hmrc/pillar2externalteststub/validation/ValidationError.scala, test/uk/gov/hmrc/pillar2externalteststub/models/orn/ORNValidationRulesSpec.scala
Adds a check that fails with `422/003 - Request could not be processed` if `filedDateGIR` is a future date.
=> PIL-1942: ORN - filedDateGIR validation

app/uk/gov/hmrc/pillar2externalteststub/controllers/BTNController.scala, app/uk/gov/hmrc/pillar2externalteststub/controllers/ORNController.scala, app/uk/gov/hmrc/pillar2externalteststub/controllers/StubErrorHandler.scala, app/uk/gov/hmrc/pillar2externalteststub/controllers/UKTRController.scala, app/uk/gov/hmrc/pillar2externalteststub/controllers/actions/AuthActionFilter.scala, app/uk/gov/hmrc/pillar2externalteststub/helpers/Pillar2Helper.scala, app/uk/gov/hmrc/pillar2externalteststub/models/error/ETMPError.scala, app/uk/gov/hmrc/pillar2externalteststub/services/UKTRService.scala, it/test/uk/gov/hmrc/pillar2externalteststub/BTNISpec.scala, it/test/uk/gov/hmrc/pillar2externalteststub/ORNISpec.scala, it/test/uk/gov/hmrc/pillar2externalteststub/ObligationsAndSubmissionsISpec.scala, it/test/uk/gov/hmrc/pillar2externalteststub/UKTRSubmissionISpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/BTNControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/ORNControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/ObligationsAndSubmissionsControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/StubErrorHandlerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/SubscriptionControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/UKTRControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/actions/AuthActionFilterSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/BTNDataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/ORNDataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/Pillar2DataFixture.scala
Adds checks for the following 4 `HIP` headers, throwing a dynamic `400` if missing or invalid:
- `correlationid` (of pattern "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")
- `X-Receipt-Date` (of pattern "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z")
- `X-Originating-System` (to equal **MDTP**)
- `X-Transmitting-System` (to equal **HIP**)
=> PIL-1978: Require HIP Headers

app/uk/gov/hmrc/pillar2externalteststub/controllers/ObligationsAndSubmissionsController.scala, app/uk/gov/hmrc/pillar2externalteststub/helpers/Pillar2Helper.scala, it/test/uk/gov/hmrc/pillar2externalteststub/ObligationsAndSubmissionsISpec.scala, project/AppDependencies.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/ObligationsAndSubmissionsControllerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/TestOrgDataFixture.scala
- `dueDate` to equal the testOrg `registrationDate` + 18 months
- `canAmend` to be `true` if the query is made within 12 months from the `dueDate`. The rejection of an amendment made after this date will be implemented in [PIL-1989](https://jira.tools.tax.service.gov.uk/browse/PIL-1989)
=> PIL-2044: O&S - Fix canAmend and dueDate

app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRLiabilityReturn.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/UKTRDataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRLiabilityReturnSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/services/UKTRServiceSpec.scala
When `obligationMTT` is false, both IIR and UTPR amounts must be zero (both totals and individual entity amounts). If not, error code 093 (Invalid Return) is returned.
Changes:
- Added new validation rule `nonMTTAmountsRule` in `UKTRLiabilityReturn.scala`
- Added unit tests in `UKTRLiabilityReturnSpec.scala` 
- Added integration tests in `UKTRServiceSpec.scala`
=> PIL-1990 - Add validation for IIR and UTPR amounts when MTT obligation is false

app/uk/gov/hmrc/pillar2externalteststub/helpers/SubscriptionHelper.scala, app/uk/gov/hmrc/pillar2externalteststub/models/organisation/TestOrganisation.scala, app/uk/gov/hmrc/pillar2externalteststub/models/orn/ORNValidationRules.scala, app/uk/gov/hmrc/pillar2externalteststub/models/orn/ORNValidator.scala, app/uk/gov/hmrc/pillar2externalteststub/services/BTNService.scala, app/uk/gov/hmrc/pillar2externalteststub/services/OrganisationService.scala, app/uk/gov/hmrc/pillar2externalteststub/services/UKTRService.scala, it/test/uk/gov/hmrc/pillar2externalteststub/BTNISpec.scala, it/test/uk/gov/hmrc/pillar2externalteststub/UKTRSubmissionISpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/actions/AuthActionFilterSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/TestOrgDataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/models/organisation/OrganisationDetailsSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/models/orn/ORNBtnValidationSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/repositories/OrganisationRepositorySpec.scala, test/uk/gov/hmrc/pillar2externalteststub/services/BTNServiceSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/services/UKTRServiceSpec.scala
Implements BTN (Below Threshold Notification) flag status validation for Overseas Return Notification (ORN) submissions as per EPID 1457 requirements. The validation checks the organisation's account status and returns error code 003 when the BTN flag is active (inactive = true).
=> PIL-1995 ORN Implement BTN Active Check

app/uk/gov/hmrc/pillar2externalteststub/controllers/ObligationsAndSubmissionsController.scala, app/uk/gov/hmrc/pillar2externalteststub/controllers/StubErrorHandler.scala, app/uk/gov/hmrc/pillar2externalteststub/models/btn/BTNValidator.scala, app/uk/gov/hmrc/pillar2externalteststub/models/error/ETMPError.scala, app/uk/gov/hmrc/pillar2externalteststub/models/organisation/TestOrganisation.scala, app/uk/gov/hmrc/pillar2externalteststub/services/OrganisationService.scala, it/test/uk/gov/hmrc/pillar2externalteststub/OrganisationISpec.scala, test/uk/gov/hmrc/pillar2externalteststub/controllers/StubErrorHandlerSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/Pillar2DataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/TestOrgDataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/models/organisation/OrganisationDetailsSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/services/BTNServiceSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/services/OrganisationServiceSpec.scala
To better match downstream and be used in validation later
To create a test organisation with an accounting period under enquiry:
```{
"orgDetails": {
"domesticOnly": false,
"organisationName": "Test Organisation Ltd",
"registrationDate": "2024-01-01"
},
"accountingPeriod": {
"startDate": "2024-01-01",
"endDate": "2024-12-31",
"underEnquiry": true
}
}
=> PIL-2049: Add optional underEnquiry field to testOrg accounting periods

app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRLiabilityReturn.scala, app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRNilReturn.scala, test/uk/gov/hmrc/pillar2externalteststub/helpers/UKTRDataFixture.scala, test/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRLiabilityReturnSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRNilReturnSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/services/UKTRServiceSpec.scala
This change updates the validation for UKTR submissions to align with ETMP's business rules for Minimum Top-up Tax (MTT) liabilities. The new logic prevents the submission of inconsistent data based on the group's registration type and MTT obligation status.
The following validation rules have been implemented:
*   A submission from a 'Domestic only' group is rejected if it contains IIR or UTPR liabilities.
*   A submission from an 'MNE & UK' group with `obligationMTT` set to `false` is rejected if it contains IIR or UTPR liabilities.
**Technical Changes:**
*   Removed the obsolete `obligationMTTRule` from the validation rules.
*   Introduced a new `mttLiabilityValidationRule` in `UKTRLiabilityReturn` with the updated logic.
*   Updated unit tests to cover the new validation scenarios and …
=> PIL-2356 - Update obligation MTT logic

app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRLiabilityReturn.scala, app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRNilReturn.scala, app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRValidationRules.scala, test/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRLiabilityReturnSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRNilReturnSpec.scala, test/uk/gov/hmrc/pillar2externalteststub/services/UKTRServiceSpec.scala
ETMP does not have validation on whether UKGAAP must be true or false based on whether it is a domestic or non-domestic organisation. We will be matching their implementation by removing all UKGAAP validation in this PR
=> [PIL-2360] - remove UKGAAP validation

app/uk/gov/hmrc/pillar2externalteststub/models/uktr/UKTRLiabilityReturn.scala
The validation for those two fields is now handled at the API layer, their validation rules here are kept for added security.
=> PIL-2359: idType and idValue - align validation with downstream
